### ISSUE TITLE
Add "message will be sent at [time]" label

### ISSUE THREAD

**Issue by jonedavis** [twilio-labs/sample-appointment-reminders-node#29]
After selecting time of appointment and when to send notification, calculate and display the time that the appointment will be sent so that user does not have to do math in their head.

**Comment by Lewiscowles1986** [comment]
Fixed up failing test from #35 so this should be a thing 
<img width="1202" alt="Screenshot 2020-01-16 at 08 10 38" src="https://user-images.githubusercontent.com/2605791/72505367-b2a90700-3837-11ea-8601-4e692bdb6fd9.png">
