### ISSUE TITLE
Add "send notification 2 minutes from now" button

### ISSUE THREAD

**Issue by jonedavis** [twilio-labs/sample-appointment-reminders-node#30]
Have a button that says "create example appointment" that schedules an appointment and will trigger the notification in 2 minutes time.

**Comment by Lewiscowles1986** [comment]
Rather than very many specific buttons would you be happy with a send at `{datetime}` button?

**Comment by Lewiscowles1986** [comment]
I may have missed something here. For some reason I thought you wanted to set the date to 2 minutes from now, but you want a custom time before appointment to notify the user.
